INSERT INTO flashcards (deck_id, question, answer, sort_order)
SELECT deck_id, question, answer, sort_order
FROM jsonb_to_recordset($cards$[
{"deck_id":"4483-sayili-kanun","question":"İlçede görevli memur hakkında soruşturma izni vermeye kim yetkilidir?","answer":"Kaymakam","sort_order":19},
{"deck_id":"4483-sayili-kanun","question":"İlde veya merkez ilçede görevli memur hakkında soruşturma izni vermeye kim yetkilidir?","answer":"Vali","sort_order":20},
{"deck_id":"4483-sayili-kanun","question":"Büyükşehir belediye başkanı hakkında soruşturma izni vermeye kim yetkilidir?","answer":"İçişleri Bakanı","sort_order":21},
{"deck_id":"4483-sayili-kanun","question":"İl veya ilçe belediye başkanı hakkında soruşturma izni vermeye kim yetkilidir?","answer":"İçişleri Bakanı","sort_order":22},
{"deck_id":"4483-sayili-kanun","question":"TBMM'de görevli memur hakkında soruşturma izni vermeye kim yetkilidir?","answer":"TBMM Genel Sekreteri","sort_order":23},
{"deck_id":"4483-sayili-kanun","question":"TBMM Genel Sekreteri veya yardımcısı hakkında soruşturma izni vermeye kim yetkilidir?","answer":"TBMM Başkanı","sort_order":24},
{"deck_id":"4483-sayili-kanun","question":"Cumhurbaşkanlığında görevli memur hakkında soruşturma izni vermeye kim yetkilidir?","answer":"Cumhurbaşkanlığı Genel Sekreteri","sort_order":25},
{"deck_id":"4483-sayili-kanun","question":"Kaymakam hakkında soruşturma izni vermeye kim yetkilidir?","answer":"Vali","sort_order":26},
{"deck_id":"4483-sayili-kanun","question":"Kaymakam hakkında hazırlık soruşturmasını kim yürütür?","answer":"İl Cumhuriyet başsavcısı veya başsavcıvekili","sort_order":27},
{"deck_id":"4483-sayili-kanun","question":"Kaymakam hakkında açılan davaya hangi mahkeme bakar?","answer":"İl ağır ceza mahkemesi","sort_order":28},
{"deck_id":"4483-sayili-kanun","question":"Vali, TBMM Genel Sekreteri, Cumhurbaşkanlığı Genel Sekreteri ve bakan yardımcısı hakkında davaya hangi mahkeme bakar?","answer":"Yargıtayın ilgili ceza dairesi","sort_order":29},
{"deck_id":"4483-sayili-kanun","question":"Soruşturma izni kararı vermek için esas süre kaç gündür?","answer":"30 gün","sort_order":30},
{"deck_id":"4483-sayili-kanun","question":"Zorunlu hallerde bu süre en fazla ne kadar uzatılabilir?","answer":"15 gün","sort_order":31},
{"deck_id":"4483-sayili-kanun","question":"Uzatma yetkisi kaç defa kullanılabilir?","answer":"Bir defa","sort_order":32},
{"deck_id":"4483-sayili-kanun","question":"Zorunlu halde uzatma kullanılırsa azami toplam süre kaç gündür?","answer":"45 gün","sort_order":33},
{"deck_id":"4483-sayili-kanun","question":"Soruşturma izni kararlarına karşı itiraz süresi ne kadardır?","answer":"Kararın tebliğinden itibaren 10 gün","sort_order":34},
{"deck_id":"4483-sayili-kanun","question":"İtirazlar en geç ne kadar sürede karara bağlanır?","answer":"3 ay içinde","sort_order":35},
{"deck_id":"4483-sayili-kanun","question":"Soruşturma izni itirazı üzerine verilen kararların niteliği nedir?","answer":"Kesindir","sort_order":36},
{"deck_id":"4483-sayili-kanun","question":"İhbar ve şikayetlerde aranan şartlardan biri hangisidir (imza)?","answer":"Dilekçe sahibinin imzasının bulunması","sort_order":37},
{"deck_id":"4483-sayili-kanun","question":"İhbar ve şikayetlerde aranan şartlardan biri hangisidir (kişi/olay)?","answer":"Kişi veya olay belirtilmesi","sort_order":38},
{"deck_id":"4483-sayili-kanun","question":"İhbar ve şikayetlerde aranan şartlardan biri hangisidir (iddia)?","answer":"İddiaların ciddi bulgu ve belgelere dayanması","sort_order":39},
{"deck_id":"4483-sayili-kanun","question":"Başsavcılar ve izin vermeye yetkili merciler, ihbarcı/şikayetçinin kimlik bilgileri konusunda nasıl davranmalıdır?","answer":"Kimlik bilgilerini gizli tutmak zorundadır","sort_order":40},
{"deck_id":"4483-sayili-kanun","question":"İzin vermeye yetkili merci, suç işlendiğini öğrendiğinde ilk olarak hangi işlemi başlatır?","answer":"Ön inceleme","sort_order":41},
{"deck_id":"4483-sayili-kanun","question":"Ön inceleme sonucunda düzenlenen rapor kime sunulur?","answer":"İzin vermeye yetkili mercie","sort_order":42},
{"deck_id":"4483-sayili-kanun","question":"Daha önce sonuçlandırılmış bir ön inceleme konusunda kural olarak ne yapılır?","answer":"Müracaat işleme konulmaz","sort_order":43},
{"deck_id":"4483-sayili-kanun","question":"Yeni belge sunulursa daha önce sonuçlandırılmış inceleme ne olur?","answer":"Müracaat yeniden işleme konulabilir","sort_order":44},
{"deck_id":"4483-sayili-kanun","question":"Suçun hukuki niteliğinin değişmesi yeniden izin alınmasını gerektirir mi?","answer":"Hayır","sort_order":45},
{"deck_id":"4483-sayili-kanun","question":"İzin verilen olaydan tamamen ayrı bir fiil ortaya çıkarsa ne gerekir?","answer":"Yeniden soruşturma izni alınması","sort_order":46},
{"deck_id":"4483-sayili-kanun","question":"Bir suç, biri memur diğeri memur olmayan iki kişi tarafından işlenirse yargılama nasıl yapılır?","answer":"Memur olmayan kişi, memur olanla aynı mahkemede yargılanır","sort_order":47},
{"deck_id":"4483-sayili-kanun","question":"Ast memur ile üst memurun aynı fiile iştiraki halinde soruşturma izni hangi merciden istenir?","answer":"Üst memurun bağlı olduğu merciden","sort_order":48},
{"deck_id":"4483-sayili-kanun","question":"Bir görevi vekaleten yürüten kamu görevlisi hangi usule tabidir?","answer":"Vekalet ettiği asilin tabi olduğu usul","sort_order":49},
{"deck_id":"4483-sayili-kanun","question":"4483 sayılı Kanun ne zaman yürürlüğe girer?","answer":"Yayımı tarihinde","sort_order":50}
]$cards$::jsonb) AS x(deck_id text, question text, answer text, sort_order int);
