INSERT INTO flashcards (deck_id, question, answer, sort_order)
SELECT deck_id, question, answer, sort_order
FROM jsonb_to_recordset($cards$[
{"deck_id":"5442-sayili-kanun","question":"Türkiye merkezi idare kuruluşu bakımından neye bölünmüştür?","answer":"İllere; iller ilçelere, ilçeler de bucaklara","sort_order":18},
{"deck_id":"5442-sayili-kanun","question":"İl ve ilçe kurulması, kaldırılması, merkezlerinin belirtilmesi nasıl yapılır?","answer":"Kanunla","sort_order":19},
{"deck_id":"5442-sayili-kanun","question":"Bucak kurulması, kaldırılması, il/ilçe/bucak sınırlarının değiştirilmesi nasıl yapılır?","answer":"Cumhurbaşkanı onayı ile","sort_order":20},
{"deck_id":"5442-sayili-kanun","question":"Kaymakam, ilçede kimin idari yürütme vasıtasıdır?","answer":"Cumhurbaşkanının","sort_order":21},
{"deck_id":"5442-sayili-kanun","question":"İlçenin genel idaresinden kim sorumludur?","answer":"Kaymakam","sort_order":22},
{"deck_id":"5442-sayili-kanun","question":"İlçedeki genel idare teşkilatının başında bulunanlar kimlerdir?","answer":"İlçe idare şube başkanları","sort_order":23},
{"deck_id":"5442-sayili-kanun","question":"Kaymakamlar, ilçe idare şube başkanlarının birinci derecede, diğer memurların ikinci derecede neyidir?","answer":"Sicil amiri","sort_order":24},
{"deck_id":"5442-sayili-kanun","question":"Kaymakam, ilçe sınırları içindeki genel ve özel kolluk kuvvetlerinin neyidir?","answer":"Amiri","sort_order":25},
{"deck_id":"5442-sayili-kanun","question":"Kaymakam, ceza ve tevkifevlerinin muhafazasını kiminle birlikte gözetim altında bulundurur?","answer":"Cumhuriyet savcısı ile birlikte","sort_order":26},
{"deck_id":"5442-sayili-kanun","question":"İlçe idare şube başkanları görevlerinden dolayı kime karşı sorumludur?","answer":"Doğrudan doğruya kaymakama","sort_order":27},
{"deck_id":"5442-sayili-kanun","question":"Kaymakam, ilçenin bütün bucak ve köylerinin en az yarısını her yıl ne yapar?","answer":"Teftiş eder","sort_order":28},
{"deck_id":"5442-sayili-kanun","question":"Kaymakam, ilçenin işleri hakkında kiminle muhabere eder?","answer":"Bağlı bulunduğu valilerle","sort_order":29},
{"deck_id":"5442-sayili-kanun","question":"Bucak nedir?","answer":"Coğrafya, ekonomi, güvenlik ve mahalli hizmet bakımından ilişkili kasaba ve köylerden oluşan idare bölümü","sort_order":30},
{"deck_id":"5442-sayili-kanun","question":"Bucak müdürü, bucakta neyin en büyük memuru ve temsilcisidir?","answer":"Hükümetin","sort_order":31},
{"deck_id":"5442-sayili-kanun","question":"Genel ve özel kolluk kuvvetleri bucakta hangi makamın emri altındadır?","answer":"Bucak müdürünün","sort_order":32},
{"deck_id":"5442-sayili-kanun","question":"Bucağın güven ve düzeninin korunmasından kim sorumludur?","answer":"Bucak müdürü","sort_order":33},
{"deck_id":"5442-sayili-kanun","question":"Bucak müdürü olağanüstü hallerde kaymakamla muhabere mümkün olmazsa ne yapar?","answer":"En yakın idare üstüne bildirir, valiliğin haberdar edilmesini ister","sort_order":34},
{"deck_id":"5442-sayili-kanun","question":"Bucak müdürü her yıl bucağın köy ve kasabalarını en az kaç kere dolaşır?","answer":"Birer kere","sort_order":35},
{"deck_id":"5442-sayili-kanun","question":"Nahiye müdürleri kimin kararıyla valilikler emrine tayin olunur?","answer":"İçişleri Bakanlığınca","sort_order":36},
{"deck_id":"5442-sayili-kanun","question":"Nahiye müdürlüğü adaylığı için askerlik hizmetini bitirmiş olma yaşı üst sınırı kaçtır?","answer":"30","sort_order":37},
{"deck_id":"5442-sayili-kanun","question":"Bucak müdürlüğü kaç sınıftan oluşur?","answer":"Altı sınıf","sort_order":38},
{"deck_id":"5442-sayili-kanun","question":"Bucak meclisi yılda kaç defa ve hangi ay toplanır?","answer":"Bir defa, Ekim ayı başında","sort_order":39},
{"deck_id":"5442-sayili-kanun","question":"Bucak komisyonu kaç üyeden oluşur?","answer":"Dört üye","sort_order":40},
{"deck_id":"5442-sayili-kanun","question":"Bucak komisyonu en az hangi sıklıkla toplanır?","answer":"Ayda bir kere","sort_order":41},
{"deck_id":"5442-sayili-kanun","question":"İl idare kurulu kimin başkanlığında toplanır?","answer":"Valinin","sort_order":42},
{"deck_id":"5442-sayili-kanun","question":"Vali, idare kuruluna başkanlık etmek üzere kimi görevlendirebilir?","answer":"Vali muavinini","sort_order":43},
{"deck_id":"5442-sayili-kanun","question":"İlçe idare kurulu kimin başkanlığında toplanır?","answer":"Kaymakamın","sort_order":44},
{"deck_id":"5442-sayili-kanun","question":"İdare kurulları kaç tür karar alır?","answer":"İdari, istişari ve kazai","sort_order":45},
{"deck_id":"5442-sayili-kanun","question":"İdare kurullarının kazai/idari/istişari görüşmeleri hangi çoğunlukla yapılabilir?","answer":"Mürettep üyenin yarısından bir fazlası hazır olmadıkça yapılamaz","sort_order":46},
{"deck_id":"5442-sayili-kanun","question":"Oyların eşitliği halinde hangi taraf çokluk sayılır?","answer":"Başkanın bulunduğu taraf","sort_order":47},
{"deck_id":"5442-sayili-kanun","question":"İdari davaya esas kararı vermiş idare amiri, idare kurulunun kazai toplantısında ne yapabilir?","answer":"Üye olamaz, oya katılamaz","sort_order":48},
{"deck_id":"5442-sayili-kanun","question":"İlçe idare kurulları kararlarına karşı nereye itiraz edilir?","answer":"İl idare kurullarına","sort_order":49},
{"deck_id":"5442-sayili-kanun","question":"5442 sayılı Kanun ne zaman yürürlüğe girmiştir?","answer":"31 Temmuz 1949","sort_order":50}
]$cards$::jsonb) AS x(deck_id text, question text, answer text, sort_order int);
