INSERT INTO flashcards (deck_id, question, answer, sort_order) VALUES
('2886-sayili-kanun','2886 sayılı Kanun temel olarak neyi düzenler?','Devlete ait taşınır/taşınmaz malların satım, kira, yapım gibi ihale usullerini',1),
('2886-sayili-kanun','Kanun''a göre ihale usullerinden biri değildir?','Doğrudan atama usulü',2),
('2886-sayili-kanun','İhale komisyonu en az kaç kişiden oluşur?','3 kişi',3),
('2886-sayili-kanun','Geçici teminat oranı ihale bedelinin genel olarak yüzde kaçıdır?','%3',4),
('2886-sayili-kanun','İhaleye katılamayacaklar arasında kimler sayılmaz?','Herkes',5),
('2886-sayili-kanun','Kesin teminat oranı genel olarak ihale bedelinin yüzde kaçıdır?','%6',6),
('2886-sayili-kanun','İhale kararının onaylanması kaç iş günü içinde yapılmalıdır?','15 iş günü',7),
('2886-sayili-kanun','Kanun kapsamında ''açık eksiltme'' hangi tür ihalelerde kullanılabilir?','Kanunda belirtilen tür ihalelerde teklif usulü olarak',8),
('4688-sayili-kanun','4688 sayılı Kanun temel olarak neyi düzenler?','Kamu görevlilerinin sendika kurma ve toplu sözleşme haklarını',1),
('4688-sayili-kanun','Kamu görevlileri hangi amaçla sendika kurabilir?','Üyelerinin ekonomik, sosyal ve mesleki hak/menfaatlerini korumak ve geliştirmek',2),
('4688-sayili-kanun','Toplu sözleşme görüşmeleri sonucunda uyuşmazlık halinde başvurulan kurul hangisidir?','Kamu Görevlileri Hakem Kurulu',3),
('4688-sayili-kanun','Sendika üyeliği kamu görevlisi için nasıldır?','İsteğe bağlıdır',4),
('4688-sayili-kanun','Kanun''a göre sendikaların en üst çatı kuruluşu nasıl adlandırılır?','Konfederasyon',5),
('4734-sayili-kanun','4734 sayılı Kanun''un temel amacı nedir?','Kamu hukukuna tabi idarelerin mal/hizmet alımı ve yapım ihalelerinde uygulanacak esasları düzenlemek',1),
('4734-sayili-kanun','Kanun''a göre temel ihale usulleri nelerdir?','Açık ihale usulü ve belli istekliler arasında ihale usulü (esas usuller)',2),
('4734-sayili-kanun','Kamu İhale Kurumu''nun temel görevi nedir?','İhale mevzuatının uygulanmasını izlemek ve itirazen şikâyetleri incelemek',3),
('4734-sayili-kanun','İhalelerde temel ilkelerden biri değildir?','Kayırmacılık',4),
('4734-sayili-kanun','Yaklaşık maliyet neyi ifade eder?','İdarece gerçekleştirilecek alımın tahmini bedelini',5),
('4734-sayili-kanun','Doğrudan temin usulü ne zaman kullanılabilir?','Kanunda sayılan istisnai ve acil hallerde',6),
('4734-sayili-kanun','İhalelere katılamayacak olanlar arasında hangisi sayılır?','İhaleyi yapan idarede görevli kişiler ile bunların yakınları (kanunda sayılanlar)',7),
('4734-sayili-kanun','Şikâyet başvurusu hangi süre içinde yapılmalıdır?','Kanunda belirtilen süreler içinde (ihale sürecine göre değişir)',8),
('4735-sayili-kanun','4735 sayılı Kanun neyi düzenler?','4734 sayılı Kanun''a göre yapılan ihaleler sonucu düzenlenen sözleşmelerin uygulanmasını',1),
('4735-sayili-kanun','Sözleşmelerde ''süre uzatımı'' hangi hallerde verilebilir?','Kanunda sayılan mücbir sebep ve idareden kaynaklanan nedenlerle',2),
('4735-sayili-kanun','Sözleşmenin devri kural olarak nasıldır?','İdarenin yazılı izni ile ve kanunda belirtilen şartlarla mümkündür',3),
('4735-sayili-kanun','Kesin teminat sözleşme bedeli üzerinden genel olarak ne kadardır?','%6',4),
('4735-sayili-kanun','Sözleşmenin feshi hangi hallerde söz konusu olabilir?','Yüklenicinin taahhüdünü ihlali gibi kanunda sayılan hallerde',5),
('4735-sayili-kanun','Kabul işlemleri neyi ifade eder?','Yapım/mal/hizmetin sözleşmeye uygunluğunun idarece tespit edilmesini',6),
('4735-sayili-kanun','Gecikme cezası ne zaman uygulanır?','Yüklenicinin işi süresinde tamamlamaması halinde',7),
('4735-sayili-kanun','Fiyat farkı ödenmesi hangi hallerde söz konusu olabilir?','Sözleşmede veya mevzuatta öngörülen şartlarda',8),
('5018-sayili-kanun','5018 sayılı Kanun''un temel amacı nedir?','Kamu kaynaklarının etkili, ekonomik ve verimli kullanılmasını sağlamak',1),
('5018-sayili-kanun','Kanun''a göre bütçe türlerinden biri değildir?','Şirket bilançosu',2),
('5018-sayili-kanun','Harcama yetkilisi kimdir?','Bütçeyle ödenek tahsis edilen her bir harcama biriminin en üst yöneticisi',3),
('5018-sayili-kanun','Ön mali kontrol görevi temel olarak kime aittir?','Strateji Geliştirme Birimlerine',4),
('5018-sayili-kanun','5018 sayılı Kanun''a göre stratejik plan hazırlama yükümlülüğü kimlere aittir?','Kamu idarelerine',5),
('5018-sayili-kanun','Kamu mali yönetiminin temel ilkelerinden biri değildir?','Kişisel takdir yetkisi',6),
('5018-sayili-kanun','Bütçe kesin hesap kanunu hangi organca kabul edilir?','TBMM',7),
('5018-sayili-kanun','Taşınır mal yönetiminden kim sorumludur?','Harcama yetkilisi ve taşınır kayıt yetkilisi',8),
('5018-sayili-kanun','İç denetim faaliyeti hangi amaçla yürütülür?','Kurumun risk yönetimi, kontrol ve yönetim süreçlerini değerlendirmek',9);
