INSERT INTO flashcards (deck_id, question, answer, sort_order)
SELECT deck_id, question, answer, sort_order
FROM jsonb_to_recordset($cards$[
{"deck_id":"4734-sayili-kanun","question":"4734 sayılı Kanunun amacı nedir?","answer":"Kamu hukukuna tâbi olan veya kamu kaynağı kullanan kurumların ihalelerinde uygulanacak esas ve usulleri belirlemek","sort_order":9},
{"deck_id":"4734-sayili-kanun","question":"Kanuna göre temel ihale usulleri nelerdir?","answer":"Açık ihale usulü ve belli istekliler arasında ihale usulü","sort_order":10},
{"deck_id":"4734-sayili-kanun","question":"Diğer (temel olmayan) ihale usulleri ne zaman kullanılabilir?","answer":"Kanunda belirtilen özel hallerde","sort_order":11},
{"deck_id":"4734-sayili-kanun","question":"Eşik değerlerin altında kalmak amacıyla alımlar kısımlara bölünebilir mi?","answer":"Hayır","sort_order":12},
{"deck_id":"4734-sayili-kanun","question":"Ödeneği bulunmayan bir iş için ihaleye çıkılabilir mi?","answer":"Hayır","sort_order":13},
{"deck_id":"4734-sayili-kanun","question":"Mal alımı, hizmet alımı ve yapım işleri bir arada ihale edilebilir mi?","answer":"Hayır, doğal bir bağlantı olmadıkça edilemez","sort_order":14},
{"deck_id":"4734-sayili-kanun","question":"İhale komisyonunca alınan kararlar ve tutanaklar nasıl imzalanır?","answer":"Başkan ve üyelerin ad, soyad ve görev unvanları belirtilerek","sort_order":15},
{"deck_id":"4734-sayili-kanun","question":"Komisyon başkanı ve üyeleri oy ve kararlarından sorumlu mudur?","answer":"Evet","sort_order":16},
{"deck_id":"4734-sayili-kanun","question":"İhale işlem dosyası, ilân veya daveti izleyen kaç gün içinde komisyon üyelerine verilir?","answer":"Üç gün","sort_order":17},
{"deck_id":"4734-sayili-kanun","question":"İhalesi yapılacak her iş için ne düzenlenir?","answer":"Bir işlem dosyası","sort_order":18},
{"deck_id":"4734-sayili-kanun","question":"İdari ve teknik şartnamelerin hazırlanması esas olarak kime aittir?","answer":"İdarelere","sort_order":19},
{"deck_id":"4734-sayili-kanun","question":"Teknik şartnamelerde belirli bir marka veya modele yönelik tanımlamalara yer verilebilir mi?","answer":"Hayır","sort_order":20},
{"deck_id":"4734-sayili-kanun","question":"Yaklaşık maliyet ihale ve ön yeterlik ilanlarında açıklanır mı?","answer":"Hayır, açıklanmaz","sort_order":21},
{"deck_id":"4734-sayili-kanun","question":"Yaklaşık maliyet hangi vergi hariç tutularak belirlenir?","answer":"Katma değer vergisi hariç","sort_order":22},
{"deck_id":"4734-sayili-kanun","question":"İş bitirme, yönetim veya denetim suretiyle elde edilen belgeler devredilebilir mi?","answer":"Hayır, devredilemez, kiraya verilemez, satılamaz","sort_order":23},
{"deck_id":"4734-sayili-kanun","question":"Yapımla ilgili hizmet işlerinden elde edilen belgeler yapım işlerinde kullanılabilir mi?","answer":"Hayır, kullanılamaz","sort_order":24},
{"deck_id":"4734-sayili-kanun","question":"İhaleyi yapan idare bünyesindeki vakıf, dernek, birlik gibi kuruluşlar o idarenin ihalelerine katılabilir mi?","answer":"Hayır, katılamazlar","sort_order":25},
{"deck_id":"4734-sayili-kanun","question":"İhale konusu işin yüklenicileri o işin danışmanlık hizmeti ihalelerine katılabilir mi?","answer":"Hayır, katılamazlar","sort_order":26},
{"deck_id":"4734-sayili-kanun","question":"Katılım yasağına rağmen ihaleye katılanlara ne yapılır?","answer":"İhale dışı bırakılır, geçici teminatları gelir kaydedilir","sort_order":27},
{"deck_id":"4734-sayili-kanun","question":"İş ortaklığı hangi ihalelere teklif verebilir?","answer":"Her türlü ihaleye","sort_order":28},
{"deck_id":"4734-sayili-kanun","question":"İş ortaklığı ile konsorsiyum arasındaki temel fark nedir?","answer":"İş ortaklığı işin tümünü birlikte, konsorsiyum ise kendi uzmanlık alanına göre ayrı ayrı yapar","sort_order":29},
{"deck_id":"4734-sayili-kanun","question":"İş ortaklığı anlaşmasında ve konsorsiyum anlaşmasında hangi ortaklar belirtilir?","answer":"İş ortaklığında pilot ortak, konsorsiyumda koordinatör ortak","sort_order":30},
{"deck_id":"4734-sayili-kanun","question":"İhalenin iş ortaklığı/konsorsiyum üzerinde kalması halinde sözleşme öncesi ne istenir?","answer":"Noter tasdikli iş ortaklığı veya konsorsiyum sözleşmesi","sort_order":31},
{"deck_id":"4734-sayili-kanun","question":"Alt yüklenicilerin yaptığı işlerdeki sorumluluk yükleniciden kalkar mı?","answer":"Hayır, yüklenicinin sorumluluğu ortadan kalkmaz","sort_order":32},
{"deck_id":"4734-sayili-kanun","question":"İhalenin iptali halinde verilmiş teklifler ne olur?","answer":"Reddedilmiş sayılır, açılmadan isteklilere iade edilir","sort_order":33},
{"deck_id":"4734-sayili-kanun","question":"Sahte belge veya sahte teminat düzenlemek/kullanmak Kanuna göre nasıl değerlendirilir?","answer":"Yasaktır","sort_order":34},
{"deck_id":"4734-sayili-kanun","question":"Uygulama projesi bulunan yapım işlerinde hangi teklif türü zorunludur?","answer":"Anahtar teslimi götürü bedel teklifi","sort_order":35},
{"deck_id":"4734-sayili-kanun","question":"İhale saati neye göre tespit edilir?","answer":"Çalışma saati dikkate alınarak","sort_order":36},
{"deck_id":"4734-sayili-kanun","question":"Kanunda yazılı sürelerin hesaplanmasında hüküm bulunmayan hallerde hangi kanun uygulanır?","answer":"Borçlar Kanunu","sort_order":37},
{"deck_id":"4734-sayili-kanun","question":"Kanunda hüküm bulunmayan tebliğler için hangi kanun uygulanır?","answer":"Tebligat Kanunu","sort_order":38},
{"deck_id":"4734-sayili-kanun","question":"Elektronik ortamda veya faksla yapılan bildirimlerde tebliğ tarihi nedir?","answer":"Bildirim tarihi","sort_order":39},
{"deck_id":"4734-sayili-kanun","question":"Kanundaki eşik değerler ve parasal limitler hangi endekse göre güncellenir?","answer":"Bir önceki yılın Toptan Eşya Fiyat Endeksi","sort_order":40},
{"deck_id":"4734-sayili-kanun","question":"Eşik değer güncellemesini kim yapar ve ne zaman ilan edilir?","answer":"Kamu İhale Kurumu, her yıl 1 Şubat'a kadar Resmî Gazete'de","sort_order":41},
{"deck_id":"4734-sayili-kanun","question":"Olağanüstü hallerde eşik değerler, belirtilen tarih dışında da kimin kararıyla güncellenebilir?","answer":"Kurumun teklifi üzerine Cumhurbaşkanı Kararı ile","sort_order":42},
{"deck_id":"4734-sayili-kanun","question":"Kanun hükümlerine ilişkin değişiklikler nasıl yapılabilir?","answer":"Ancak bu Kanuna hüküm eklenmek veya Kanunda değişiklik yapılmak suretiyle","sort_order":43},
{"deck_id":"4734-sayili-kanun","question":"Ön ilan yapılması halinde ilan ve davet süresi ne kadara indirilebilir?","answer":"Kırk günden yirmidört güne","sort_order":44},
{"deck_id":"4734-sayili-kanun","question":"Ön ilan yapılmış olması idareye ihale yapma yükümlülüğü getirir mi?","answer":"Hayır, getirmez","sort_order":45},
{"deck_id":"4734-sayili-kanun","question":"Zeyilname düzenlenmesi halinde önceden teklif vermiş isteklilere ne imkânı sağlanır?","answer":"Tekliflerini geri çekip yeniden teklif verme imkânı","sort_order":46},
{"deck_id":"4734-sayili-kanun","question":"Personel çalıştırılmasına dayalı hizmet alımına örnek nedir?","answer":"Park-bahçe bakımı, çöp toplama gibi sürekli mahalli idare hizmetleri","sort_order":47},
{"deck_id":"4734-sayili-kanun","question":"Yerli malı belirlenmesine ilişkin usul ve esasları kim belirler?","answer":"İlgili kurum ve kuruluşların görüşleri alınarak yetkili bakanlık","sort_order":48},
{"deck_id":"4734-sayili-kanun","question":"Ortak girişimlerin yerli istekli sayılabilmesi için şart nedir?","answer":"Bütün ortaklarının yerli istekli olması","sort_order":49},
{"deck_id":"4734-sayili-kanun","question":"İhale konusu mal veya hizmet alımı ile yapım işlerinin teknik kriterleri nerede belirtilir?","answer":"İhale dokümanının parçası olan teknik şartnamelerde","sort_order":50}
]$cards$::jsonb) AS x(deck_id text, question text, answer text, sort_order int);
