INSERT INTO flashcards (deck_id, question, answer, sort_order)
SELECT deck_id, question, answer, sort_order
FROM jsonb_to_recordset($cards$[
{"deck_id":"4735-sayili-kanun","question":"4735 sayılı Kanunun amacı nedir?","answer":"Kamu İhale Kanununa göre yapılan ihalelere ilişkin sözleşmelerin düzenlenmesi ve uygulanması ile ilgili esas ve usulleri belirlemek","sort_order":9},
{"deck_id":"4735-sayili-kanun","question":"4735 sayılı Kanunun kapsamı nedir?","answer":"Kamu İhale Kanununa tabi kurum ve kuruluşların o Kanuna göre yaptığı ihaleler sonucu düzenlenen sözleşmeler","sort_order":10},
{"deck_id":"4735-sayili-kanun","question":"4735 sayılı Kanunun uygulanmasında hangi Kanundaki tanımlar geçerlidir?","answer":"4734 sayılı Kamu İhale Kanunu'ndaki tanımlar","sort_order":11},
{"deck_id":"4735-sayili-kanun","question":"Sözleşme hükümlerinde Kanunda belirtilen haller dışında ne yapılamaz?","answer":"Değişiklik yapılamaz, ek sözleşme düzenlenemez","sort_order":12},
{"deck_id":"4735-sayili-kanun","question":"İdarelerce yapılacak sözleşmeler neye göre düzenlenir?","answer":"Tip Sözleşme hükümleri esas alınarak","sort_order":13},
{"deck_id":"4735-sayili-kanun","question":"Tip Sözleşmeler nerede yayımlanır?","answer":"Resmî Gazete'de","sort_order":14},
{"deck_id":"4735-sayili-kanun","question":"Yapım işlerinde uygulama projelerine dayalı, toplam bedel üzerinden yapılan sözleşme türü nedir?","answer":"Anahtar teslimi götürü bedel sözleşme","sort_order":15},
{"deck_id":"4735-sayili-kanun","question":"Mal/hizmet alımında idarece belirlenen işin tamamı için toplam bedel üzerinden yapılan sözleşme türü nedir?","answer":"Götürü bedel sözleşme","sort_order":16},
{"deck_id":"4735-sayili-kanun","question":"İdarece hazırlanmış cetveldeki iş kalemi miktarı ile birim fiyatın çarpımına dayalı sözleşme türü nedir?","answer":"Birim fiyat sözleşme","sort_order":17},
{"deck_id":"4735-sayili-kanun","question":"Bir kısmı anahtar teslimi götürü bedel, bir kısmı birim fiyat olan sözleşme türüne ne denir?","answer":"Karma sözleşme","sort_order":18},
{"deck_id":"4735-sayili-kanun","question":"Çerçeve anlaşmaya dayalı olarak idare ile yüklenici arasında imzalanan sözleşmeye ne denir?","answer":"Münferit sözleşme","sort_order":19},
{"deck_id":"4735-sayili-kanun","question":"Sözleşmede belirtilmesi zorunlu hususlardan biri hangisidir?","answer":"İşin adı, niteliği, türü ve miktarı","sort_order":20},
{"deck_id":"4735-sayili-kanun","question":"Sözleşmede varsa hangi bilgiler yer almalıdır?","answer":"Alt yüklenicilere ilişkin bilgiler ve sorumlulukları","sort_order":21},
{"deck_id":"4735-sayili-kanun","question":"Kanunda hüküm bulunmayan hallerde teminatlar için hangi Kanun uygulanır?","answer":"Kamu İhale Kanunu","sort_order":22},
{"deck_id":"4735-sayili-kanun","question":"Kanunda hüküm bulunmayan hallerde genel olarak hangi Kanun uygulanır?","answer":"Borçlar Kanunu","sort_order":23},
{"deck_id":"4735-sayili-kanun","question":"Kanunda hüküm bulunmayan tebliğler hakkında hangi Kanun uygulanır?","answer":"Tebligat Kanunu","sort_order":24},
{"deck_id":"4735-sayili-kanun","question":"4735 sayılı Kanun ne zaman yürürlüğe girmiştir?","answer":"1.1.2003 tarihinde","sort_order":25},
{"deck_id":"4735-sayili-kanun","question":"Fiyat farkı esas ve usullerini tespite kimin teklifi üzerine kim yetkilidir?","answer":"Kamu İhale Kurumunun teklifi üzerine Cumhurbaşkanı","sort_order":26},
{"deck_id":"4735-sayili-kanun","question":"Fiyat farkına ilişkin esaslarda sözleşme imzalandıktan sonra değişiklik yapılabilir mi?","answer":"Hayır","sort_order":27},
{"deck_id":"4735-sayili-kanun","question":"Mücbir sebep sayılabilmesi için yüklenicinin idareye bildirimi hangi süre içinde yapılmalıdır?","answer":"Mücbir sebebin meydana geldiği tarihi izleyen yirmi gün içinde","sort_order":28},
{"deck_id":"4735-sayili-kanun","question":"Mücbir sebep örneklerinden biri hangisidir?","answer":"Kısmî veya genel seferberlik ilânı","sort_order":29},
{"deck_id":"4735-sayili-kanun","question":"Ortak girişimlerde pilot/koordinatör ortak dışındaki bir ortağın ölümü, iflası vb. sözleşmenin devamına engel midir?","answer":"Hayır","sort_order":30},
{"deck_id":"4735-sayili-kanun","question":"Pilot veya koordinatör ortağın ölümü halinde ne olur?","answer":"Sözleşme feshedilerek işler tasfiye edilir, kesin teminat iade edilir","sort_order":31},
{"deck_id":"4735-sayili-kanun","question":"Yüklenicinin mali acz nedeniyle taahhüdünü yerine getiremeyeceğini bildirmesi halinde ne olur?","answer":"Kesin teminat gelir kaydedilir, sözleşme feshedilerek tasfiye edilir","sort_order":32},
{"deck_id":"4735-sayili-kanun","question":"Yüklenicinin taahhüdünü yerine getirmemesi üzerine idarenin ihtarı en az kaç gün süreli olmalıdır?","answer":"On gün","sort_order":33},
{"deck_id":"4735-sayili-kanun","question":"Bu Kanun kapsamındaki işlerden dolayı ceza almış olanlar ne yapamaz?","answer":"Bu Kanun kapsamındaki kadrolara atanamaz ve görev alamazlar","sort_order":34},
{"deck_id":"4735-sayili-kanun","question":"Muayene ve kabul komisyonu üyelerinin tarafsız davranmadığının tespiti halinde ne uygulanır?","answer":"Disiplin cezası","sort_order":35},
{"deck_id":"4735-sayili-kanun","question":"Görevliler ve danışmanlık hizmeti sunanlar yüklenicilere ait gizli bilgileri ne yapamaz?","answer":"İfşa edemez, kendileri veya üçüncü şahıslar yararına kullanamaz","sort_order":36},
{"deck_id":"4735-sayili-kanun","question":"Yapım işlerinde yüklenici ve alt yükleniciler kesin kabul onay tarihinden itibaren kaç yıl süreyle müteselsilen sorumludur?","answer":"Onbeş yıl","sort_order":37},
{"deck_id":"4735-sayili-kanun","question":"Yapı denetim görevlilerinin sorumluluğu nasıl giderilir?","answer":"Zarar ve ziyan genel hükümlere göre kendilerine tazmin ettirilir","sort_order":38},
{"deck_id":"4735-sayili-kanun","question":"Kamu İhale Kanununa göre yapılan sözleşmeler açısından hangi Kanun hükümleri uygulanmaz?","answer":"2886 sayılı Devlet İhale Kanunu","sort_order":39},
{"deck_id":"4735-sayili-kanun","question":"Sözleşme uygulamalarından kaynaklanan anlaşmazlıkların çözümü için hangi kurula başvurulabilir?","answer":"Yüksek Fen Kurulu","sort_order":40},
{"deck_id":"4735-sayili-kanun","question":"Yüksek Fen Kurulu itirazları en geç kaç gün içinde karara bağlar?","answer":"Altmış gün","sort_order":41},
{"deck_id":"4735-sayili-kanun","question":"Yüksek Fen Kuruluna başvurabilmek için hangi şart aranır?","answer":"Anlaşmazlığın yargılama veya Sayıştay incelemesine konu edilmemiş olması","sort_order":42},
{"deck_id":"4735-sayili-kanun","question":"Sözleşmenin uygulanması sırasında yüklenicinin yasak fiil veya davranışlarda bulunduğunun tespiti sözleşmeyi nasıl sonuçlandırır?","answer":"Kesin teminat gelir kaydedilerek fesih ve tasfiye","sort_order":43},
{"deck_id":"4735-sayili-kanun","question":"Bu Kanuna aykırı fiillerden hüküm giyen idare görevlileri ne yapamaz?","answer":"Bu Kanun kapsamındaki işlerde görevlendirilemez","sort_order":44},
{"deck_id":"4735-sayili-kanun","question":"2985 sayılı Toplu Konut Kanunu kapsamındaki sözleşmelerde özel usul ve esasları belirlemeye kim yetkilidir?","answer":"Cumhurbaşkanı","sort_order":45},
{"deck_id":"4735-sayili-kanun","question":"Sözleşmede ödeme yeri ve şartlarıyla birlikte hangi husus belirtilir?","answer":"Avans verilip verilmeyeceği, verilecekse şartları ve miktarı","sort_order":46},
{"deck_id":"4735-sayili-kanun","question":"Kanunun ikinci bölümü hangi başlığı taşır?","answer":"Sözleşmelerin Düzenlenmesi","sort_order":47},
{"deck_id":"4735-sayili-kanun","question":"Sözleşme dokümanında ihale dokümanına aykırı hükümlere yer verilebilir mi?","answer":"Hayır, verilemez","sort_order":48},
{"deck_id":"4735-sayili-kanun","question":"4735 sayılı Kanun hangi Kanuna göre yapılan ihalelerin sözleşmelerini kapsar?","answer":"4734 sayılı Kamu İhale Kanunu","sort_order":49},
{"deck_id":"4735-sayili-kanun","question":"İş ortaklığı ve konsorsiyum ortaklarından birinin dağılması/ölümü halinde diğer ortaklar ne yapar?","answer":"O ortağın sorumluluklarını da üstlenerek taahhüdü yerine getirirler","sort_order":50}
]$cards$::jsonb) AS x(deck_id text, question text, answer text, sort_order int);
