INSERT INTO flashcards (deck_id, question, answer, sort_order)
SELECT deck_id, question, answer, sort_order
FROM jsonb_to_recordset($cards$[
{"deck_id":"4688-sayili-kanun","question":"Sendika ve konfederasyonlar kurulmak için önceden izin almaları gerekir mi?","answer":"Hayır, önceden izin almaksızın serbestçe kurulurlar","sort_order":6},
{"deck_id":"4688-sayili-kanun","question":"Sendika kurucusu olabilmek için hangi şart yeterlidir?","answer":"Kamu görevlisi olarak çalışmak","sort_order":7},
{"deck_id":"4688-sayili-kanun","question":"Sendika veya konfederasyon ne zaman tüzel kişilik kazanır?","answer":"Belge ve tüzüklerin ilgili valiliğe verilmesiyle","sort_order":8},
{"deck_id":"4688-sayili-kanun","question":"Valilik, tüzük ve belgelerin bir örneğini kaç işgünü içinde Çalışma ve Sosyal Güvenlik Bakanlığına gönderir?","answer":"Onbeş işgünü","sort_order":9},
{"deck_id":"4688-sayili-kanun","question":"Bir hizmet kolunda birden fazla sendika kurulabilir mi?","answer":"Evet","sort_order":10},
{"deck_id":"4688-sayili-kanun","question":"Meslek veya işyeri esasına göre sendika kurulabilir mi?","answer":"Hayır, kurulamaz","sort_order":11},
{"deck_id":"4688-sayili-kanun","question":"Sendikaların kurulabileceği hizmet kollarından biri hangisidir?","answer":"Eğitim, öğretim ve bilim hizmetleri","sort_order":12},
{"deck_id":"4688-sayili-kanun","question":"Sendika tüzüğünde bulunması gereken hususlardan biri hangisidir?","answer":"Sendikanın faaliyet göstereceği hizmet kolu","sort_order":13},
{"deck_id":"4688-sayili-kanun","question":"Sendika şubesi ve sendika yönetim kurulları kaç üyeden oluşur?","answer":"En az üç, en çok yedi üyeden","sort_order":14},
{"deck_id":"4688-sayili-kanun","question":"Disiplin ve denetleme kurulları kaç üyeden oluşur?","answer":"En az üç, en çok beş üyeden","sort_order":15},
{"deck_id":"4688-sayili-kanun","question":"Konfederasyon genel kurulları en çok kaç delegeden oluşur?","answer":"Beşyüz delege","sort_order":16},
{"deck_id":"4688-sayili-kanun","question":"Sendika şubesi genel kurulları ve üye sayısı 1000'i aşan sendikaların genel kurulları nasıl yapılabilir?","answer":"Delegelerle","sort_order":17},
{"deck_id":"4688-sayili-kanun","question":"Delegeler nasıl seçilir?","answer":"Gizli oy, açık sayım ve döküm esasına göre","sort_order":18},
{"deck_id":"4688-sayili-kanun","question":"Sendika veya konfederasyonun ilk genel kurulu, tüzel kişilik kazanmasından itibaren kaç ay içinde yapılır?","answer":"Altı ay","sort_order":19},
{"deck_id":"4688-sayili-kanun","question":"Olağan genel kurul toplantıları en fazla kaç yılı aşmamak üzere yapılır?","answer":"Dört yıl","sort_order":20},
{"deck_id":"4688-sayili-kanun","question":"Genel kurullarda seçimler nasıl yapılır?","answer":"Yargı gözetimi altında serbest, eşit, gizli oy, açık sayım ve döküm esasına göre","sort_order":21},
{"deck_id":"4688-sayili-kanun","question":"Kamu görevlileri hangi sendikaya üye olabilir?","answer":"Çalıştıkları işyerinin girdiği hizmet kolunda kurulu bir sendikaya","sort_order":22},
{"deck_id":"4688-sayili-kanun","question":"Üyelik başvurusu sendika tarafından reddedilmezse ne olur?","answer":"En çok otuz gün içinde reddedilmezse üyelik kabul edilmiş sayılır","sort_order":23},
{"deck_id":"4688-sayili-kanun","question":"Sendikadan çekilme, işverene başvuru tarihinden itibaren ne zaman geçerli olur?","answer":"Otuz gün sonra","sort_order":24},
{"deck_id":"4688-sayili-kanun","question":"Üyenin sendikadan çıkarılma kararını hangi organ verir?","answer":"Sendika merkez genel kurulu","sort_order":25},
{"deck_id":"4688-sayili-kanun","question":"Çıkarılan üyelerin isimleri sendikaca kaç gün içinde işverene bildirilmelidir?","answer":"Onbeş gün","sort_order":26},
{"deck_id":"4688-sayili-kanun","question":"Sendikalar en fazla kaç konfederasyona üye olabilir?","answer":"Yalnızca bir konfederasyona","sort_order":27},
{"deck_id":"4688-sayili-kanun","question":"Kamu işvereni sendika üyesi olan ve olmayan görevliler arasında ayrım yapabilir mi?","answer":"Hayır","sort_order":28},
{"deck_id":"4688-sayili-kanun","question":"Kamu görevlileri sendikaları ile konfederasyonlar toplu sözleşme görüşmelerinde neye yetkilidir?","answer":"Taraf olmaya","sort_order":29},
{"deck_id":"4688-sayili-kanun","question":"Sendika ve konfederasyonlar kamu makamlarından maddi yardım kabul edebilir mi?","answer":"Hayır","sort_order":30},
{"deck_id":"4688-sayili-kanun","question":"Sendika ve konfederasyonlar siyasi partilerden maddi yardım alabilir mi?","answer":"Hayır","sort_order":31},
{"deck_id":"4688-sayili-kanun","question":"Sendika ve konfederasyonlar ticaretle uğraşabilir mi?","answer":"Hayır","sort_order":32},
{"deck_id":"4688-sayili-kanun","question":"Kamu Personeli Danışma Kurulu her yıl hangi aylarda toplanır?","answer":"Mart ve Kasım","sort_order":33},
{"deck_id":"4688-sayili-kanun","question":"Kurulun sekretarya hizmetlerini hangi kurum yürütür?","answer":"Devlet Personel Başkanlığı","sort_order":34},
{"deck_id":"4688-sayili-kanun","question":"Kurum İdari Kurulları yılda kaç kez toplanır?","answer":"İki kez","sort_order":35},
{"deck_id":"4688-sayili-kanun","question":"İşyeri sendika temsilcisi seçme yetkisi hangi sendikaya aittir?","answer":"İşyerinde en çok üye kaydetmiş sendikaya","sort_order":36},
{"deck_id":"4688-sayili-kanun","question":"İşyeri sendika temsilcileri görevlerini haftada kaç saat yerine getirir ve izinli sayılır?","answer":"Dört saat","sort_order":37},
{"deck_id":"4688-sayili-kanun","question":"Sendika ve konfederasyonların gelirleri nelerden oluşur?","answer":"Üyelik ödentileri, faaliyet gelirleri, bağış ve yardımlar, mal varlığı gelirleri","sort_order":38},
{"deck_id":"4688-sayili-kanun","question":"Konfederasyonlara ödenecek ödenti miktarı sendika ödenti tutarının yüzde kaçından aşağı olamaz?","answer":"Yüzde beş","sort_order":39},
{"deck_id":"4688-sayili-kanun","question":"Sendika ve konfederasyonlar gelirlerinin en az yüzde kaçını üyelerin mesleki bilgi/tecrübesini artırmak için kullanmak zorundadır?","answer":"Yüzde on","sort_order":40},
{"deck_id":"4688-sayili-kanun","question":"Sendika tüzüğüne üyelik ödentisi dışında başka kesinti öngören hükümler konulabilir mi?","answer":"Hayır","sort_order":41},
{"deck_id":"4688-sayili-kanun","question":"Sendika ve konfederasyonlar bilanço, hesap ve denetleme raporlarını hangi süre içinde Bakanlığa gönderir?","answer":"İzleyen üç ay içinde","sort_order":42},
{"deck_id":"4688-sayili-kanun","question":"Vergi Usul Kanununa göre demirbaş sayılan eşyalar nasıl işlem görür?","answer":"Demirbaş defterine kaydedilir, gider olarak işlem göremez","sort_order":43},
{"deck_id":"4688-sayili-kanun","question":"20, 24 ve 26. maddelere aykırı hareket edenlere hangi ceza uygulanır?","answer":"Altı aydan bir yıla kadar hapis cezası","sort_order":44},
{"deck_id":"4688-sayili-kanun","question":"Fesih, infisah veya kapatma halinde kalacak para ve mallar tüzükte aksi yoksa nereye devredilir?","answer":"Hazineye","sort_order":45},
{"deck_id":"4688-sayili-kanun","question":"4688 sayılı Kanun ne zaman yürürlüğe girmiştir?","answer":"Yayımını takip eden 30. günün sonunda","sort_order":46},
{"deck_id":"4688-sayili-kanun","question":"4688 sayılı Kanun hükümlerini kim yürütür?","answer":"Bakanlar Kurulu","sort_order":47},
{"deck_id":"4688-sayili-kanun","question":"Sendika genel kurullarının görev ve yetkilerinden biri hangisidir?","answer":"Yönetim ve denetleme kurulu raporlarının görüşülmesi ve aklanması","sort_order":48},
{"deck_id":"4688-sayili-kanun","question":"Genel kurulun görevlerinden biri olarak taşınmaz mal alım/satımı için ne yapılır?","answer":"Yönetim kuruluna yetki verilmesi","sort_order":49},
{"deck_id":"4688-sayili-kanun","question":"Sendika şubesi açma ve kapatma yetkisi hangi organa aittir?","answer":"Genel kurula","sort_order":50}
]$cards$::jsonb) AS x(deck_id text, question text, answer text, sort_order int);
