INSERT INTO flashcards (deck_id, question, answer, sort_order)
SELECT deck_id, question, answer, sort_order
FROM jsonb_to_recordset($cards$[
{"deck_id":"5018-sayili-kanun","question":"Bakanlar, kamuoyunu idarelerinin amaç, hedef, strateji ve performans programları konusunda ne zaman bilgilendirir?","answer":"Her mali yılın ilk ayı içinde","sort_order":10},
{"deck_id":"5018-sayili-kanun","question":"Bütçelerde belirli gelirlerin belirli giderlere tahsis edilmesi genel kural olarak nasıldır?","answer":"Esas olarak tahsis edilmez","sort_order":11},
{"deck_id":"5018-sayili-kanun","question":"Bütçelerde gelir-gider dengesi konusunda temel yaklaşım nedir?","answer":"Denklik sağlanması esastır","sort_order":12},
{"deck_id":"5018-sayili-kanun","question":"Merkezi yönetim bütçesi hangi cetvellerdeki idarelerin bütçelerinden oluşur?","answer":"I, II ve III sayılı cetveller","sort_order":13},
{"deck_id":"5018-sayili-kanun","question":"Genel yönetim kapsamındaki idareler bütçe uygulama sonuçlarını hangi ay kamuoyuna açıklar?","answer":"Temmuz ayı içinde","sort_order":14},
{"deck_id":"5018-sayili-kanun","question":"Sayıştay, kesin hesap kanun teklifinin verilmesinden itibaren en geç kaç gün içinde genel uygunluk bildirimini TBMM'ye sunar?","answer":"Yetmiş beş gün","sort_order":15},
{"deck_id":"5018-sayili-kanun","question":"Merkezi yönetim bütçe kanun teklifi mali yılbaşından en az kaç gün önce TBMM'ye sunulur?","answer":"Yetmiş beş gün","sort_order":16},
{"deck_id":"5018-sayili-kanun","question":"Kesin hesap kanunu teklifi izleyen mali yılın hangi ayı sonuna kadar TBMM'ye sunulur?","answer":"Haziran ayı sonuna kadar","sort_order":17},
{"deck_id":"5018-sayili-kanun","question":"Bütçe kanun teklifi süresinde yürürlüğe konulamazsa ne çıkarılır?","answer":"Geçici bütçe kanunu","sort_order":18},
{"deck_id":"5018-sayili-kanun","question":"Harcama yetkisi kime aittir?","answer":"Bütçeyle ödenek tahsis edilen harcama biriminin en üst yöneticisine","sort_order":19},
{"deck_id":"5018-sayili-kanun","question":"Harcama yetkisinin devri, yetkiyi devredenin hangi sorumluluğunu ortadan kaldırmaz?","answer":"İdari sorumluluğunu","sort_order":20},
{"deck_id":"5018-sayili-kanun","question":"Bütçeden harcama yapılabilmesi neyle mümkündür?","answer":"Harcama yetkilisinin harcama talimatı vermesiyle","sort_order":21},
{"deck_id":"5018-sayili-kanun","question":"Harcama yetkilisi ile muhasebe yetkilisi görevi aynı kişide birleşebilir mi?","answer":"Hayır","sort_order":22},
{"deck_id":"5018-sayili-kanun","question":"Muhasebe yetkilisi olacakların en az kaç yıllık yüksek öğrenim görmüş olması şarttır?","answer":"En az dört yıllık","sort_order":23},
{"deck_id":"5018-sayili-kanun","question":"Muhasebe yetkilisi olacaklar hangi belgeyi almış olmalıdır?","answer":"Muhasebe yetkilisi sertifikası","sort_order":24},
{"deck_id":"5018-sayili-kanun","question":"Genel bütçe kapsamındaki idarelerde muhasebe yetkilisini kim atar?","answer":"Hazine ve Maliye Bakanlığı","sort_order":25},
{"deck_id":"5018-sayili-kanun","question":"İç denetçi olarak atanacakların kamu idarelerinde denetim elemanı olarak en az kaç yıl çalışmış olması gerekir?","answer":"En az beş yıl","sort_order":26},
{"deck_id":"5018-sayili-kanun","question":"Bakanlıklarda iç denetçiler kimin teklifiyle kim tarafından atanır?","answer":"Üst yöneticilerin teklifi üzerine Bakan tarafından","sort_order":27},
{"deck_id":"5018-sayili-kanun","question":"İç denetçi görevinde bağımsız mıdır, asli görevi dışında görev verilebilir mi?","answer":"Bağımsızdır, asli görevi dışında görev verilemez","sort_order":28},
{"deck_id":"5018-sayili-kanun","question":"İç denetçiler raporlarını doğrudan kime sunar?","answer":"Üst yöneticiye","sort_order":29},
{"deck_id":"5018-sayili-kanun","question":"İç denetim raporları üst yönetici tarafından en geç kaç ay içinde İç Denetim Koordinasyon Kuruluna gönderilir?","answer":"İki ay","sort_order":30},
{"deck_id":"5018-sayili-kanun","question":"İç Denetim Koordinasyon Kurulu hangi bakanlığa bağlıdır ve kaç üyeden oluşur?","answer":"Hazine ve Maliye Bakanlığına bağlı, yedi üyeli","sort_order":31},
{"deck_id":"5018-sayili-kanun","question":"İç kontrol sistemini idare adına kim oluşturur?","answer":"İdarenin kendisi","sort_order":32},
{"deck_id":"5018-sayili-kanun","question":"Ön mali kontrol, harcama birimlerindeki kontrollerle birlikte hangi birimin kontrollerini kapsar?","answer":"Mali hizmetler birimi","sort_order":33},
{"deck_id":"5018-sayili-kanun","question":"Ön ödeme (avans/kredi) hangi tür giderler için yapılabilir?","answer":"Gerçekleştirme işlemlerinin tamamlanması beklenemeyecek ivedi veya zorunlu giderler","sort_order":34},
{"deck_id":"5018-sayili-kanun","question":"Mutemet, kredilerdeki ön ödeme harcamalarını kaç ay içinde belgelendirmekle yükümlüdür?","answer":"Üç ay","sort_order":35},
{"deck_id":"5018-sayili-kanun","question":"Yüklenicilere teminat karşılığında bütçe dışı avans, yüklenme tutarının yüzde kaçını geçemez?","answer":"Yüzde otuz","sort_order":36},
{"deck_id":"5018-sayili-kanun","question":"Yedek ödenek, genel bütçe ödeneklerinin yüzde kaçına kadar konulabilir?","answer":"Yüzde iki","sort_order":37},
{"deck_id":"5018-sayili-kanun","question":"Yedek ödenekten aktarma yapmaya kim yetkilidir?","answer":"Cumhurbaşkanı","sort_order":38},
{"deck_id":"5018-sayili-kanun","question":"Kamu idareleri, kendi bütçeleri içinde bir tertipteki ödeneğin yüzde kaçına kadar aktarma yapabilir?","answer":"Yüzde yirmi","sort_order":39},
{"deck_id":"5018-sayili-kanun","question":"Cari yılda kullanılmayan ödeneklere yıl sonunda ne olur?","answer":"İptal edilir","sort_order":40},
{"deck_id":"5018-sayili-kanun","question":"Örtülü ödenek hangi bütçeye konulan bir ödenektir?","answer":"Cumhurbaşkanlığı bütçesine","sort_order":41},
{"deck_id":"5018-sayili-kanun","question":"Örtülü ödenek tutarı, genel bütçe başlangıç ödenekleri toplamının binde kaçını geçemez?","answer":"Binde beş","sort_order":42},
{"deck_id":"5018-sayili-kanun","question":"Genel bütçe kapsamındaki idarelerin edindiği taşınmazlar kimin adına tescil edilir?","answer":"Hazine adına","sort_order":43},
{"deck_id":"5018-sayili-kanun","question":"Merkezi yönetim kapsamındaki idarelerin sınır üstü değerdeki taşınmazları kimin kararıyla satılır?","answer":"Cumhurbaşkanı kararıyla","sort_order":44},
{"deck_id":"5018-sayili-kanun","question":"Kamu iktisadi teşebbüsleri ve kamu şirketlerinden gayrisafi hasılatının yüzde kaçına kadar bedel tahsil edilip genel bütçeye gelir kaydedilir?","answer":"Yüzde on beş","sort_order":45},
{"deck_id":"5018-sayili-kanun","question":"Mali yıl hangi dönemi ifade eder?","answer":"Takvim yılını","sort_order":46},
{"deck_id":"5018-sayili-kanun","question":"Malın alındığı yılı izleyen beşinci yılın sonuna kadar talep edilmeyen emanet hesaplarındaki tutarlar ne olur?","answer":"Bütçeye gelir kaydedilir","sort_order":47},
{"deck_id":"5018-sayili-kanun","question":"Kamu zararına neden olanlara, bir aylık net ödemelerinin kaç katına kadar para cezası verilir?","answer":"İki katına kadar","sort_order":48},
{"deck_id":"5018-sayili-kanun","question":"Para cezaları, ilgililerin bir aylık net ödemelerinin hangi oranında kesilerek tahsil olunur?","answer":"Dörtte biri oranında","sort_order":49},
{"deck_id":"5018-sayili-kanun","question":"Malî yönetim ve kontrol sisteminin zaafa uğradığı durumlarda kamu idarelerini kim teftiş ettirir?","answer":"Cumhurbaşkanı","sort_order":50}
]$cards$::jsonb) AS x(deck_id text, question text, answer text, sort_order int);
