INSERT INTO flashcards (deck_id, question, answer, sort_order)
SELECT deck_id, question, answer, sort_order
FROM jsonb_to_recordset($cards$[
{"deck_id":"2886-sayili-kanun","question":"İhale komisyonunu görevlendiren makam hangisidir?","answer":"İta amirleri","sort_order":9},
{"deck_id":"2886-sayili-kanun","question":"Şartname ve ekleri idarede nasıl görülebilir?","answer":"Bedelsiz","sort_order":10},
{"deck_id":"2886-sayili-kanun","question":"İhale komisyonu kararlarında çekimser kalınabilir mi?","answer":"Hayır, kararlar çoğunlukla alınır, çekimser kalınamaz","sort_order":11},
{"deck_id":"2886-sayili-kanun","question":"Tahmin edilen bedel kural olarak kim tarafından tespit edilir?","answer":"İdarelerce","sort_order":12},
{"deck_id":"2886-sayili-kanun","question":"Kanunda kaç temel ihale usulü sayılmıştır?","answer":"5","sort_order":13},
{"deck_id":"2886-sayili-kanun","question":"Kanunun 1. maddesindeki işlerin ihalelerinde esas usul hangisidir?","answer":"Kapalı teklif usulü","sort_order":14},
{"deck_id":"2886-sayili-kanun","question":"Kapalı teklif usulünde teklifler nasıl yapılır?","answer":"Yazılı olarak","sort_order":15},
{"deck_id":"2886-sayili-kanun","question":"Dış zarflar hangi sırayla açılır?","answer":"Alınış sırasına göre","sort_order":16},
{"deck_id":"2886-sayili-kanun","question":"Tekliflerin ayrıntılı incelenmesi gerekiyorsa ihale en fazla kaç gün ertelenebilir?","answer":"15 gün","sort_order":17},
{"deck_id":"2886-sayili-kanun","question":"Belli istekliler arasında kapalı teklif usulünde kural olarak en az kaç istekli bulunur?","answer":"3","sort_order":18},
{"deck_id":"2886-sayili-kanun","question":"Açık teklif usulünde ihaleden çekilenler yeniden teklifte bulunabilir mi?","answer":"Hayır","sort_order":19},
{"deck_id":"2886-sayili-kanun","question":"Önceden düşünülmesi mümkün olmayan acele işler hangi usulle yapılabilir?","answer":"Pazarlık usulüyle","sort_order":20},
{"deck_id":"2886-sayili-kanun","question":"İdareler etüt, plan, proje ve güzel sanatlara ilişkin işleri hangi usulle yaptırabilir?","answer":"Yarışma usulüyle","sort_order":21},
{"deck_id":"2886-sayili-kanun","question":"İhalenin yapılacağı yerde ilk ilan ile ihale günü arasındaki süre en az kaç gündür?","answer":"10 gün","sort_order":22},
{"deck_id":"2886-sayili-kanun","question":"Son ilan ile ihale günü arasındaki süre en az kaç gündür?","answer":"5 gün","sort_order":23},
{"deck_id":"2886-sayili-kanun","question":"İlan yapıldıktan sonra şartname ve eklerinde değişiklik yapılabilir mi?","answer":"Hayır, değişiklik yapılamaz","sort_order":24},
{"deck_id":"2886-sayili-kanun","question":"Yabancı ülkelerde yapılacak ilan, ihale gününden en az kaç gün önce yapılır?","answer":"45 gün","sort_order":25},
{"deck_id":"2886-sayili-kanun","question":"Kesin teminat ne zaman alınır?","answer":"Sözleşme yapılmasından önce","sort_order":26},
{"deck_id":"2886-sayili-kanun","question":"Sözleşme yapıldıktan sonra geçici teminata ne olur?","answer":"İade edilir","sort_order":27},
{"deck_id":"2886-sayili-kanun","question":"Sözleşme idare adına kim tarafından imzalanır?","answer":"İta amiri","sort_order":28},
{"deck_id":"2886-sayili-kanun","question":"Yapım işlerinde geçici kabul sonrası şartlar sağlanırsa kesin teminatın ne kadarı geri verilebilir?","answer":"Yarısı","sort_order":29},
{"deck_id":"2886-sayili-kanun","question":"Müteahhit taahhüdünü uygun yerine getirmezse idarenin ihtarı en az kaç gün süreli olmalıdır?","answer":"10 gün","sort_order":30},
{"deck_id":"2886-sayili-kanun","question":"Yapım işlerinde öngörülmeyen iş artışında müteahhit keşif bedelinin hangi oranına kadar değişikliği yapmakla yükümlüdür?","answer":"%30","sort_order":31},
{"deck_id":"2886-sayili-kanun","question":"Keşif bedeli artışı %30'u geçerse ne olur?","answer":"Sözleşme feshedilir","sort_order":32},
{"deck_id":"2886-sayili-kanun","question":"Kiraya verilecek taşınır ve taşınmaz malların kira süresi kural olarak en çok kaç yıldır?","answer":"10 yıl","sort_order":33},
{"deck_id":"2886-sayili-kanun","question":"Su ürünleri istihsal hakkı kiralarında idareler kural olarak kaç yıla kadar sözleşme yapabilir?","answer":"5 yıl","sort_order":34},
{"deck_id":"2886-sayili-kanun","question":"Sözleşmenin devri için ne gerekir?","answer":"İta amirinin yazılı izni","sort_order":35},
{"deck_id":"2886-sayili-kanun","question":"Müteahhit veya müşterinin iflası halinde sözleşmeye ne olur?","answer":"Bozulur","sort_order":36},
{"deck_id":"2886-sayili-kanun","question":"Eksiltmelerde uygun bedel için hangi sınır geçerlidir?","answer":"Tahmin edilen bedeli geçmemesi","sort_order":37},
{"deck_id":"2886-sayili-kanun","question":"Komisyonlar ihaleyi yapmama kararı verebilir mi?","answer":"Evet, gerekçesini belirtmek suretiyle; karar kesindir","sort_order":38},
{"deck_id":"2886-sayili-kanun","question":"İhale kararları ita amirince karar tarihinden itibaren en geç kaç işgünü içinde onaylanır veya iptal edilir?","answer":"15 işgünü","sort_order":39},
{"deck_id":"2886-sayili-kanun","question":"Onaylanan ihale kararı, ihale üzerinde kalana en geç kaç işgünü içinde bildirilir?","answer":"5 işgünü","sort_order":40},
{"deck_id":"2886-sayili-kanun","question":"İhaleye ilişkin işlemlere hile, tehdit veya çıkar sağlama yoluyla fesat karıştırmak hangi hükme tabidir?","answer":"Yasaktır","sort_order":41},
{"deck_id":"2886-sayili-kanun","question":"İhalelere katılmaktan yasaklama kararı nerede ilan edilir?","answer":"Resmî Gazete'de","sort_order":42},
{"deck_id":"2886-sayili-kanun","question":"83. maddedeki fiiller nedeniyle mahkemece verilecek ihalelere girmekten yasaklama süresi hangi aralıktadır?","answer":"1 yıldan 3 yıla kadar","sort_order":43},
{"deck_id":"2886-sayili-kanun","question":"Hileli malzeme veya teknik icaplara aykırı yapım nedeniyle sorumluluk, kesin kabulden itibaren kaç yıl sürer?","answer":"5 yıl","sort_order":44},
{"deck_id":"2886-sayili-kanun","question":"Ecrimisil tespitinde geriye doğru azami süre kaç yıldır?","answer":"5 yıl","sort_order":45},
{"deck_id":"2886-sayili-kanun","question":"Ecrimisile itiraz edilmemesi halinde uygulanacak indirim oranı nedir?","answer":"%20","sort_order":46},
{"deck_id":"2886-sayili-kanun","question":"Ecrimisilin peşin ödenmesi halinde ayrıca uygulanacak indirim oranı nedir?","answer":"%15","sort_order":47},
{"deck_id":"2886-sayili-kanun","question":"Tarihi ve bedii değeri olan taşınmazların kiraya verilmesinde hangi Bakanlığın görüşü alınır?","answer":"Kültür ve Turizm Bakanlığının","sort_order":48},
{"deck_id":"2886-sayili-kanun","question":"2886 sayılı Devlet İhale Kanunu hangi tarihte yürürlüğe girmiştir?","answer":"1 Ocak 1984","sort_order":49},
{"deck_id":"2886-sayili-kanun","question":"2886 sayılı Kanun hükümlerini kim yürütür?","answer":"Bakanlar Kurulu","sort_order":50}
]$cards$::jsonb) AS x(deck_id text, question text, answer text, sort_order int);
