
insert into card_questions (id, deck_id, prompt, options, answer_index, sort_order) values
('is3','idare-sistemi','Türkiye''de idare teşkilatı esas olarak hangi iki ana yönetim biçimine dayanır?', '["Üniter yönetim ve federal yönetim","Merkezden yönetim ve yerinden yönetim","Parlamenter yönetim ve başkanlık yönetimi","Demokratik yönetim ve otokratik yönetim"]', 1, 3),
('is4','idare-sistemi','Yetki genişliği ilkesi öncelikle hangi idare biriminin yönetiminde uygulanır?', '["Köy","İlçe","İl","Belediye"]', 2, 4),
('is5','idare-sistemi','İlin idari başı kimdir?', '["Kaymakam","Vali","Belediye Başkanı","Muhtar"]', 1, 5),
('is6','idare-sistemi','İlçenin idari başı kimdir?', '["Vali","Kaymakam","Vali Yardımcısı","Belediye Başkanı"]', 1, 6),
('is7','idare-sistemi','Vali, hangi makamın kararıyla atanır?', '["İçişleri Bakanı kararıyla tek başına","Cumhurbaşkanı kararıyla","TBMM kararıyla","Bakanlar Kurulu kararıyla"]', 1, 7),
('is8','idare-sistemi','Kaymakamların atanma süreciyle ilgili aşağıdakilerden hangisi doğrudur?', '["Vali tarafından doğrudan atanır","İçişleri Bakanlığının süreci içinde atanır","Herhangi bir teklif olmaksızın kendi kendine göreve başlar","İl Genel Meclisi kararıyla atanır"]', 1, 8),
('is9','idare-sistemi','İl İdare Kurulu''nun başkanı kimdir?', '["Vali","Hukuk İşleri Müdürü","Defterdar","İl Emniyet Müdürü"]', 0, 9),
('is10','idare-sistemi','Aşağıdakilerden hangisi il idare şube başkanlarından biri değildir?', '["Milli Eğitim Müdürü","Defterdar","İl Emniyet Müdürü","Belediye Başkanı"]', 3, 10),
('is11','idare-sistemi','İl özel idaresinin karar organı hangisidir?', '["İl Encümeni","İl Genel Meclisi","Vali","İl Daimi Komisyonu"]', 1, 11),
('is12','idare-sistemi','İl özel idaresinin yürütme organı ve başı kimdir?', '["İl Genel Meclisi Başkanı","Vali","İl Encümeni","Kaymakam"]', 1, 12),
('is13','idare-sistemi','İl Özel İdaresi Kanunu''nun sayısı kaçtır?', '["5216","5302","5393","442"]', 1, 13),
('is14','idare-sistemi','Belediye Kanunu''nun sayısı kaçtır?', '["5216","5302","5393","1580"]', 2, 14),
('is15','idare-sistemi','Büyükşehir Belediyesi Kanunu''nun sayısı kaçtır?', '["5216","5302","5393","3030"]', 0, 15),
('is16','idare-sistemi','Belediyenin karar organı hangisidir?', '["Belediye Encümeni","Belediye Meclisi","Belediye Başkanı","İl Genel Meclisi"]', 1, 16),
('is17','idare-sistemi','Belediye tüzel kişiliğinin başı ve yürütme organı kimdir?', '["Belediye Meclisi Başkanı","Belediye Başkanı","Encümen Başkanı","Vali"]', 1, 17),
('is18','idare-sistemi','Genel kural olarak belediye kurulabilmesi için asgari nüfus şartı nedir?', '["2.000","5.000","10.000","50.000"]', 1, 18),
('is19','idare-sistemi','Bir ilde büyükşehir belediyesi kurulabilmesi için toplam il nüfusu en az kaç olmalıdır?', '["500.000","750.000","1.000.000","2.000.000"]', 1, 19),
('is20','idare-sistemi','Köyün karar organı hangisidir?', '["Köy Derneği","İhtiyar Meclisi","Muhtar","Köy Encümeni"]', 1, 20),
('is21','idare-sistemi','Köyün yürütme organı ve kanuni temsilcisi kimdir?', '["İhtiyar Meclisi Başkanı","Muhtar","Vali","Kaymakam"]', 1, 21),
('is22','idare-sistemi','Mahallenin yönetiminde görevli organ hangisidir?', '["Mahalle Meclisi","Muhtar ve İhtiyar Heyeti","Mahalle Encümeni","Belediye Meclisi"]', 1, 22),
('is23','idare-sistemi','Köy Kanunu kaç sayılıdır?', '["442","4541","5216","1580"]', 0, 23),
('is24','idare-sistemi','Aşağıdakilerden hangisi merkezi idarenin başkent (merkez) teşkilatı içinde yer alır?', '["Valilik","Kaymakamlık","Bakanlıklar","Belediye"]', 2, 24),
('is25','idare-sistemi','Aşağıdakilerden hangisi merkezi idarenin taşra teşkilatı içinde yer alır?', '["Cumhurbaşkanlığı merkez teşkilatı","Bakanlık merkez teşkilatı","Valilik","TBMM"]', 2, 25),
('is26','idare-sistemi','Hizmet yönünden yerinden yönetim kuruluşlarına örnek olarak aşağıdakilerden hangisi verilebilir?', '["İl özel idaresi","Belediye","Üniversiteler","Köy"]', 2, 26),
('is27','idare-sistemi','Aşağıdakilerden hangisi yer yönünden (yer bakımından) yerinden yönetim kuruluşu değildir?', '["İl özel idaresi","Belediye","Köy","Üniversite"]', 3, 27),
('is28','idare-sistemi','Vali, ilde kimi/kimleri temsil eder?', '["Sadece merkezi idareyi","Sadece il özel idaresini","Hem merkezi idareyi hem il özel idaresini","Sadece TBMM''yi"]', 2, 28),
('is29','idare-sistemi','İdari vesayet denetimi kimin üzerinde, kim tarafından uygulanır?', '["Merkezi idare üzerinde yerinden yönetimin","Yerinden yönetim kuruluşları üzerinde merkezi idarenin","Yalnızca belediyeler üzerinde valinin","TBMM üzerinde Cumhurbaşkanının"]', 1, 29),
('is30','idare-sistemi','Aşağıdakilerden hangisi idari vesayetin amaçlarından biri değildir?', '["Kamu yararının korunması","Ülke bütünlüğünün korunması","Hizmetlerde birlik ve bütünlük sağlanması","Hiyerarşik amir-memur ilişkisi kurulması"]', 3, 30),
('is31','idare-sistemi','İdari vesayet ile hiyerarşi arasındaki temel farklardan biri aşağıdakilerden hangisidir?', '["Vesayet ayrı tüzel kişiler arasında, hiyerarşi aynı tüzel kişilik içinde uygulanır","İkisi aynı anlama gelir","Vesayet sadece belediyelerde uygulanır","Hiyerarşi sadece köylerde uygulanır"]', 0, 31),
('is32','idare-sistemi','İl genel meclisi üyeleri kaç yılda bir seçilir?', '["4 yıl","5 yıl","6 yıl","3 yıl"]', 1, 32),
('is33','idare-sistemi','Belediye başkanı kaç yılda bir seçilir?', '["4 yıl","5 yıl","7 yıl","2 yıl"]', 1, 33),
('is34','idare-sistemi','Muhtar kaç yılda bir seçilir?', '["4 yıl","5 yıl","6 yıl","3 yıl"]', 1, 34),
('is35','idare-sistemi','İlçe kurulması, kaldırılması veya adının değiştirilmesi hangi işlemle yapılır?', '["Bakanlar Kurulu kararıyla","Kanunla","Cumhurbaşkanı kararnamesiyle","Vali kararıyla"]', 1, 35),
('is36','idare-sistemi','6360 sayılı Kanun ile büyükşehir belediyesi sınırları içinde hangi idari birimlerin tüzel kişiliği kaldırılmıştır?', '["İl özel idaresi ve mahalle","Köy ve belde","Belediye ve muhtarlık","İlçe ve bucak"]', 1, 36),
('is37','idare-sistemi','6360 sayılı Kanun''a göre büyükşehir belediyelerinin sınırları neresi olarak kabul edilmiştir?', '["İlçe belediye sınırları","İl mülki sınırları","Eski belediye sınırları","Mahalle sınırları"]', 1, 37),
('is38','idare-sistemi','6360 sayılı Kanun sonrası büyükşehir sınırları içindeki köyler hangi statüye dönüştürülmüştür?', '["Belde","Mahalle","İlçe","Kasaba"]', 1, 38),
('is39','idare-sistemi','İl özel idaresinin tüzel kişiliği hangi kanun kapsamındaki büyükşehirlerde kaldırılmıştır?', '["Sadece İstanbul''da özel bir kanunla","6360 sayılı Kanun kapsamındaki büyükşehirlerde","Hiçbir yerde kaldırılmamıştır","Sadece köylerde"]', 1, 39),
('is40','idare-sistemi','Aşağıdakilerden hangisi ayrı bir kamu tüzel kişisi değildir?', '["Belediye","İl özel idaresi","Köy","Bakanlık"]', 3, 40),
('is41','idare-sistemi','İl encümeninin başkanı kimdir?', '["İl Genel Meclisi Başkanı","Vali","Kaymakam","Defterdar"]', 1, 41),
('is42','idare-sistemi','Belediye encümeninin başkanı kimdir?', '["Meclis Başkanı","Belediye Başkanı","En yaşlı üye","Encümen Müdürü"]', 1, 42),
('is43','idare-sistemi','Aşağıdakilerden hangisi valinin görevlerinden biri değildir?', '["İlde kamu düzenini sağlamak","İl özel idaresini temsil etmek","Kanunların uygulanmasını sağlamak","Yasama yetkisini kullanmak"]', 3, 43),
('is44','idare-sistemi','Kaymakam, ilçede öncelikle kimin/kimlerin temsilcisi konumundadır?', '["Sadece TBMM''nin","Vali ve hükümetin","Sadece belediyenin","Sadece İl Genel Meclisinin"]', 1, 44),
('is45','idare-sistemi','Merkezi idarenin taşrada birden fazla ili kapsayacak şekilde kurduğu yönetim birimine ne ad verilir?', '["Bölge kuruluşu","İl özel idaresi","Bucak","Muhtarlık"]', 0, 45),
('is46','idare-sistemi','Aşağıdakilerden hangisi il düzeyinde merkezi idarenin taşra teşkilatı kuruluşlarından biridir?', '["Belediye Meclisi","Defterdarlık","İl Genel Meclisi","Muhtarlık"]', 1, 46),
('is47','idare-sistemi','5442 sayılı İl İdaresi Kanunu''na göre Türkiye''nin idari kuruluşunda temel birim aşağıdakilerden hangisidir?', '["Köy","İlçe","İl","Mahalle"]', 2, 47),
('is48','idare-sistemi','Belediye meclisi üye sayısı temel olarak neye göre değişir?', '["Belediyenin yüzölçümüne göre","Belediyenin nüfusuna göre","Belediye başkanının tercihine göre","Valinin kararına göre"]', 1, 48),
('is49','idare-sistemi','İdarenin bütünlüğü ilkesi Anayasa''nın hangi maddesinde düzenlenmiştir?', '["123. madde","104. madde","90. madde","10. madde"]', 0, 49),
('is50','idare-sistemi','Anayasa''ya göre Türkiye''nin idari kuruluşu hangi esaslara göre düzenlenir?', '["Sadece merkezden yönetim esasına göre","Sadece yerinden yönetim esasına göre","Merkezden yönetim ve yerinden yönetim esaslarına göre","Federal esasa göre"]', 2, 50);
