INSERT INTO flashcards (deck_id, question, answer, sort_order)
SELECT deck_id, question, answer, sort_order
FROM jsonb_to_recordset($cards$[
{"deck_id":"4982-sayili-kanun","question":"4982 sayılı Kanuna göre bilgi edinme hakkına kim sahiptir?","answer":"Herkes","sort_order":15},
{"deck_id":"4982-sayili-kanun","question":"4982 sayılı Kanun hükümlerini kim yürütür?","answer":"Cumhurbaşkanı","sort_order":16},
{"deck_id":"4982-sayili-kanun","question":"4982 sayılı Kanun karşısında 3071 sayılı Dilekçe Hakkı Kanunu hükümlerinin durumu nedir?","answer":"Saklıdır","sort_order":17},
{"deck_id":"4982-sayili-kanun","question":"Erişilen bilgi ve belgeler hangi amaçla çoğaltılıp kullanılamaz?","answer":"Ticari amaçla","sort_order":18},
{"deck_id":"4982-sayili-kanun","question":"Bilgi veya belgeye erişim için genel süre kaç iş günüdür?","answer":"15 iş günü","sort_order":19},
{"deck_id":"4982-sayili-kanun","question":"Başka birimden bilgi/görüş gerektiren hallerde erişim süresi en fazla kaç iş günüdür?","answer":"30 iş günü","sort_order":20},
{"deck_id":"4982-sayili-kanun","question":"Erişim maliyetinin bildirilmesi 15 iş günlük süreyi nasıl etkiler?","answer":"Süreyi keser","sort_order":21},
{"deck_id":"4982-sayili-kanun","question":"Bilgi Edinme Değerlendirme Kurulu kaç üyeden oluşur?","answer":"9 üye","sort_order":22},
{"deck_id":"4982-sayili-kanun","question":"Kurul üyelerinin görev süresi kaç yıldır?","answer":"4 yıl","sort_order":23},
{"deck_id":"4982-sayili-kanun","question":"Kurul üyelerini kim seçer?","answer":"Cumhurbaşkanı","sort_order":24},
{"deck_id":"4982-sayili-kanun","question":"Görev süresi sona eren Kurul üyesi yeniden seçilebilir mi?","answer":"Evet","sort_order":25},
{"deck_id":"4982-sayili-kanun","question":"Kurulun sekretarya hizmetlerini hangi kurum yürütür?","answer":"Adalet Bakanlığı","sort_order":26},
{"deck_id":"4982-sayili-kanun","question":"Kurul en az hangi sıklıkla toplanır?","answer":"Ayda bir defa","sort_order":27},
{"deck_id":"4982-sayili-kanun","question":"Bilgi edinme istemi reddedilen kişi Kurula ne kadar süre içinde itiraz edebilir?","answer":"Kararın tebliğinden itibaren 15 gün içinde","sort_order":28},
{"deck_id":"4982-sayili-kanun","question":"Kurul itiraz hakkındaki kararını kaç iş günü içinde verir?","answer":"30 iş günü","sort_order":29},
{"deck_id":"4982-sayili-kanun","question":"Kurula itiraz, idari yargıya başvurma süresini nasıl etkiler?","answer":"Durdurur","sort_order":30},
{"deck_id":"4982-sayili-kanun","question":"Kurum ve kuruluşlar Kurulun istediği bilgi/belgeyi kaç iş günü içinde vermelidir?","answer":"15 iş günü","sort_order":31},
{"deck_id":"4982-sayili-kanun","question":"Kurul genel raporunu TBMM'ye ne zamana kadar gönderir?","answer":"Her yıl Nisan ayı sonuna kadar","sort_order":32},
{"deck_id":"4982-sayili-kanun","question":"Kurum ve kuruluşlar bir önceki yıla ait bilgi edinme raporlarını Kurula ne zamana kadar gönderir?","answer":"Her yıl Şubat ayı sonuna kadar","sort_order":33},
{"deck_id":"4982-sayili-kanun","question":"TBMM Başkanlığına gönderilen raporlar ne kadar süre içinde kamuoyuna açıklanır?","answer":"Takip eden iki ay içinde","sort_order":34},
{"deck_id":"4982-sayili-kanun","question":"Kanunun uygulanmasına ilişkin yönetmelik kim tarafından hazırlanır?","answer":"Cumhurbaşkanlığı","sort_order":35},
{"deck_id":"4982-sayili-kanun","question":"Bu yönetmelik Kanunun yayımını takip eden ne kadar süre içinde hazırlanır?","answer":"6 ay içinde","sort_order":36},
{"deck_id":"4982-sayili-kanun","question":"Devlet sırrına ilişkin bilginin kapsam dışı sayılması için açıklanması neye zarar vermelidir?","answer":"Millî güvenliğe","sort_order":37},
{"deck_id":"4982-sayili-kanun","question":"Adli soruşturma ve kovuşturmaya ilişkin bilgi, açıklanması suç işlenmesine yol açacaksa nasıl değerlendirilir?","answer":"Kanun kapsamı dışındadır","sort_order":38},
{"deck_id":"4982-sayili-kanun","question":"Sivil ve askeri istihbarat birimlerinin görev ve faaliyetlerine ilişkin bilgiler kanun kapsamında mıdır?","answer":"Hayır, kapsam dışındadır","sort_order":39},
{"deck_id":"4982-sayili-kanun","question":"Haberleşmenin gizliliğini ihlal edecek bilgi veya belgeler kanun kapsamında mıdır?","answer":"Hayır, kapsam dışındadır","sort_order":40},
{"deck_id":"4982-sayili-kanun","question":"Ticari sır olarak nitelenen bilgi veya belgeler kanun kapsamında mıdır?","answer":"Hayır, kapsam dışındadır","sort_order":41},
{"deck_id":"4982-sayili-kanun","question":"Kamu yararı gerektiriyorsa kişisel bilgi açıklanmadan önce ilgili kişiye en az kaç gün önce haber verilmelidir?","answer":"7 gün","sort_order":42},
{"deck_id":"4982-sayili-kanun","question":"Kamu yararı nedeniyle kişisel bilginin açıklanabilmesi için ayrıca hangi şart aranır?","answer":"İlgili kişinin yazılı rızası","sort_order":43},
{"deck_id":"4982-sayili-kanun","question":"Özel hayatın gizliliği kapsamında özellikle hangi bilgiler korunur?","answer":"Kişinin sağlık bilgileri","sort_order":44},
{"deck_id":"4982-sayili-kanun","question":"Gerçek kişinin yazılı başvurusunda hangi bilgi yer almalıdır?","answer":"Adı ve soyadı","sort_order":45},
{"deck_id":"4982-sayili-kanun","question":"Tüzel kişinin başvurusunda ayrıca hangi belge aranır?","answer":"Yetki belgesi","sort_order":46},
{"deck_id":"4982-sayili-kanun","question":"Türkiye'de faaliyette bulunan yabancı tüzel kişiler hangi çerçevede Kanundan yararlanabilir?","answer":"Karşılıklılık ilkesi çerçevesinde","sort_order":47},
{"deck_id":"4982-sayili-kanun","question":"Kurumca daha önce yayımlanmış veya kamuya açıklanmış bilgiler bilgi edinme başvurusuna konu olabilir mi?","answer":"Hayır, olamaz","sort_order":48},
{"deck_id":"4982-sayili-kanun","question":"Kurum, özel bir çalışma/araştırma sonucu oluşturulabilecek bilgi talebine ne yapabilir?","answer":"Olumsuz cevap verebilir","sort_order":49},
{"deck_id":"4982-sayili-kanun","question":"Kopya çıkarılması belgenin aslına zarar verecekse yazılı belge için hangi imkân sağlanır?","answer":"Aslını inceleme ve not alma","sort_order":50}
]$cards$::jsonb) AS x(deck_id text, question text, answer text, sort_order int);
